apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-app
  namespace: argocd
spec:
  project: hypolia
  source:
    repoURL: 'https://github.com/hypolia/infrastructure.git'
    targetRevision: HEAD
    path: applications/api/chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hypolia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true