name: GCP Cloud Build CI

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      ref:
        required: true
        type: string
      repository:
        required: true
        type: string
      tag:
        required: true
        type: string
      worker_pool:
        required: true
        type: string
    secrets:
      PAT:
        required: true
      GCP_CREDENTIALS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          fetch-tags: true
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v2'
      - name: cloud build
        run: |
          gcloud builds submit \
            --tag ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.tag }} \
            --timeout=3600 \
            --worker-pool=${{ inputs.worker_pool }}
